---
title: "STAT 331 Final Project Proposal + Data"
author: "Adam Manzke, Rianna Lei, Addie Lilley, Hannah Goudz" 
format: html
---

## Introduction

Briefly introduce the focus of your project.
Mention the two quantitative variables from Gapminder that you selected, and why they are of interest.

The focus of our project is to research an association between inequality index and happiness score. We're interested in these variables because we were fascinated by the premise of quantifying happiness, and we'd like to find out if wealth inequality is related.

---

## Data and Variables

### Data Sources

- **Variable 1**: *Inequality Index* — downloaded from Gapminder ([https://data.worldbank.org/indicator/SI.POV.GINI])
- **Variable 2**: *Happiness Score* — downloaded from Gapminder ([http://gapm.io/dhapiscore_whr])

The Inequality Index is originally sourced from World Bank.


### Variables

- **Inequality Index**: Percent of inequality (percent deviation from the "ideal line", where every person in society has the same income). This is called the Gini Index. You can read more about this [here](https://en.wikipedia.org/wiki/Lorenz_curve).

- **Happiness Score**: Measurement from 0 to 100, where subjects were asked to rank their current life satisfaction, where 0 is the worst possible life for the subject and 100 is the best.

---

## Hypothesis

State your hypothesis in terms of direction and strength.

Example:
> I hypothesize that there is a strong positive relationship between GDP per capita and life expectancy. Countries with higher economic output per person are more likely to have better healthcare systems, improved living standards, and longer life spans.

> We hypothesize that there is a strong negative relationship between happiness score and inequality index. [A study](https://www.forbes.com/sites/johnjennings/2024/02/12/money-buys-happiness-after-all/) showed that happiness increases with wealth (up to a point), so in countries with more wealth inequality, more people will rate their happiness lower.

---

## Data Cleaning Process

Describe each major cleaning step you performed in R:

1. Pivoting wide to long format using `pivot_longer()`: creates new columns for year and score; necessary for joining the two data sets
2. Converting year columns to integers: makes things way nicer
3. Joining datasets on `country` and `year`: combines our two longer data sets with a left join, ensuring only years with happiness scores (happiness starts in 2004, inequality starts in 1963)
4. Removing missing values with `drop_na()`: a nice thing to do for plotting later

As mentioned above, we're limiting our analysis to years 2004 through 2023, instead of using the full inequality score data set (which starts in 1963).

```{r}
library(tidyverse)
# Read data
ineq <- read_csv("inequality_index_gini.csv")
happ <- read_csv("hapiscore_whr.csv")

# Pivot longer
ineq_long <- ineq |> 
  pivot_longer(cols = -country,
               names_to = "year",
               values_to = "inequality_score") |> 
  mutate(year = as.integer(year))

happ_long <- happ |> 
  pivot_longer(cols = -country,
               names_to = "year",
               values_to = "happ_score") |> 
  mutate(year = as.integer(year))

# Join datasets - happiness starts at 2004 whereas ineq starts at 1963,
# so only keep observations from 2004 onward
gapminder_clean <- left_join(happ_long, ineq_long, by = c("country", "year"))

# Optional: drop rows with missing data
gapminder_clean <- gapminder_clean |> 
  drop_na()

```


---

## Summary

Wrap up this section by stating the final structure of your dataset.

Example:
> The cleaned dataset includes 150 countries and spans the years 1960 to 2020. Each row represents a country-year observation, with values for both GDP per capita and life expectancy.

---

## Citations

- Gapminder: https://www.gapminder.org/data/
- WHO report on social determinants of health: https://www.who.int/publications/i/item/9789241563970
- Add any other articles or sources used to support your hypothesis.
